use_frameworks!

platform :ios, '10.0'

target 'LibUsingForkedCharts_Example' do
  pod 'LibUsingForkedCharts', :path => '../'

  target 'LibUsingForkedCharts_Tests' do
    inherit! :search_paths

    
  end
end
