use_frameworks!

platform :ios, '12.0'

target 'LibUsingForkedCharts_Example' do
  pod 'LibUsingForkedCharts', :path => '../'
  pod 'ChartsForked', :git => 'https://github.com/ag-drivequant/ChartsForked.git', :branch => 'master'

end
